/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/upload": {
    /** Upload a file */
    post: operations["uploadFile"];
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Upload a file */
  uploadFile: {
    requestBody: {
      content: {
        "multipart/form-data": {
          /**
           * Format: binary
           * @description The file to upload
           */
          file: string;
          /** @description The name of the file */
          name: string;
          query: {
            version: number;
          };
          members: string[];
        };
      };
    };
    responses: {
      /** @description File uploaded successfully */
      200: {
        content: {
          "application/json": {
            /** @example File uploaded successfully */
            message: string;
          };
        };
      };
      /** @description Invalid file */
      400: {
        content: {
          "application/json": {
            /** @example Invalid file format */
            error?: string;
          };
        };
      };
    };
  };
}
