import createClient from "openapi-fetch";
import type { paths } from "./generated-types.d.ts"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: "https://echo-server.deno.dev" });

const { data, error } = await client.POST("/upload", {
  body: {
    file: "file",
    name: "hello.txt",
    query: {
      version: 2,
    },
  },
  bodySerializer: (body) => {
    const fd = new FormData();
    for (const name in body) {
      fd.append(name, body[name as keyof typeof body]);
    }
    return fd;
  },
});

console.log(data, error);
