import createClient from "openapi-fetch";
import type { paths } from "./generated-types.d.ts"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: "http://localhost:8000" });

const { data, error } = await client.POST("/upload", {
  body: {
    file: "file",
    name: "hello.txt",
    query: {
      version: 2,
    },
    members: [
      "Alice",
      "Bob",
    ],
  },
  bodySerializer: (body) => {
    const fd = new FormData();
    for (const name in body) {
      let value = body[name as keyof typeof body];
      if (typeof value === 'object' && value !== null) {
        value = JSON.stringify(value);
      }
      fd.append(name, value);
    }
    return fd;
  },
});

console.log(data, error);
